---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  always_update_cookbooks: true
  product_name: chef
  product_version: 15

  client_rb:
    chef_license: accept

verifier:
  name: inspec

platforms:
  - name: centos-7.2

suites:
  - name: default
    run_list:
      - recipe[dockerserver::default]
    attributes:
